name = "fractal-vagal-pages"
type = "html"
# Отключаем команду сборки, так как у нас статический HTML
command = ""
# Указываем, что файлы находятся в корневой папке
root = "/"

[env.production]
# Ничего не нужно для статики
