name = "little-glade-fc4d"
# Удаляем type = "html", так как это Worker, а не Pages.
# Указываем основной файл с логикой (может быть .ts или .js)
main = "src/index.js" 
compatibility_date = "2026-01-31" # Используем вашу текущую дату из настроек

# Опционально: если ваш код использует NPM-пакеты,
# вам может понадобиться команда сборки. Если нет, оставьте пустым.
[build]
command = "" 
